### ISSUE TITLE
How to install? 

### ISSUE THREAD

**Issue by hermesalvesbr** [codihaus/directus-extension-seo#2]
I'm try to test your SEO extension, it's a great idea. Thanks for your job!

I'm trying to use inside a docker container:  `directus/directus:latest`

![Captura de tela de 2023-10-18 11-47-35](https://github.com/codihaus/directus-extension-seo/assets/379850/12e45e79-f7e4-4dfd-a79a-0ea18a7bc893)

```
43 timing command:i Completed in 3272ms
44 verbose stack Error: Unsupported URL Type "workspace:": workspace:*
44 verbose stack     at unsupportedURLType (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:327:15)
44 verbose stack     at fromURL (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:387:13)
44 verbose stack     at Function.resolve (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:83:12)
44 verbose stack     at #nodeFromEdge (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1048:22)
44 verbose stack     at #buildDepStep (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:917:35)
44 verbose stack     at #resolveLinks (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1436:32)
44 verbose stack     at #buildDepStep (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:783:32)
44 verbose stack     at #buildDepStep (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1035:30)
45 verbose cwd /directus
46 verbose Linux 5.15.0-86-generic
47 verbose node v18.18.0
48 verbose npm  v9.8.1
49 error code EUNSUPPORTEDPROTOCOL
50 error Unsupported URL Type "workspace:": workspace:*
51 verbose exit 1
52 timing npm Completed in 3406ms

```

Another way to install your extension?

**Comment by vans37** [comment]
> I'm try to test your SEO extension, it's a great idea. Thanks for your job!
> 
> I'm trying to use inside a docker container: `directus/directus:latest`
> 
> ![Captura de tela de 2023-10-18 11-47-35](https://user-images.githubusercontent.com/379850/276297562-12e45e79-f7e4-4dfd-a79a-0ea18a7bc893.png)
> 
> ```
> 43 timing command:i Completed in 3272ms
> 44 verbose stack Error: Unsupported URL Type "workspace:": workspace:*
> 44 verbose stack     at unsupportedURLType (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:327:15)
> 44 verbose stack     at fromURL (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:387:13)
> 44 verbose stack     at Function.resolve (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:83:12)
> 44 verbose stack     at #nodeFromEdge (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1048:22)
> 44 verbose stack     at #buildDepStep (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:917:35)
> 44 verbose stack     at #resolveLinks (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1436:32)
> 44 verbose stack     at #buildDepStep (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:783:32)
> 44 verbose stack     at #buildDepStep (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1035:30)
> 45 verbose cwd /directus
> 46 verbose Linux 5.15.0-86-generic
> 47 verbose node v18.18.0
> 48 verbose npm  v9.8.1
> 49 error code EUNSUPPORTEDPROTOCOL
> 50 error Unsupported URL Type "workspace:": workspace:*
> 51 verbose exit 1
> 52 timing npm Completed in 3406ms
> ```
> 
> Another way to install your extension?

Hello. Please refer to this directus docker guide: [](https://docs.directus.io/self-hosted/docker-guide.html) 
There's a specific section about persistence.
In short, you have to create volume for extensions and link it to your project extensions folder, then you can create or paste an extension. There's one more valuable options id docker-compose file which I use daily - EXTENSIONS_AUTO_RELOAD: true, which will watch for changes and reload extensions (if it's a newly copied extension then you'll have to restart your directus docker container).

Here's an example of my docker-compose.dev.yaml file: 
`backend:
      container_name: yourname-directus
      image: directus/directus:latest
      ports:  
        - ${BACKEND_PORT}:8055
      **volumes:
        - ./backend/uploads:/directus/uploads
        - ./backend/extensions:/directus/extensions**
      networks:
        - app_network
      depends_on:
        - cache
        - database
      environment:
        KEY: '${KEY}'
        SECRET: '${SECRET}'
        DB_CLIENT: 'pg'
        DB_HOST: 'database'
        DB_PORT: '5432'
        DB_DATABASE: '${POSTGRES_DB}'
        DB_USER: '${POSTGRES_USER}'
        DB_PASSWORD: '${POSTGRES_PASSWORD}'
        EXTENSIONS_AUTO_RELOAD: true
        CACHE_ENABLED: '${CACHE_ENABLED}'
        CACHE_STORE: 'redis'
        #CACHE_REDIS: 'redis://cache:6379'
        # only for dev
        CORS_ENABLED: true
        CORS_ORIGIN: "http://localhost:3000"
        REDIS: 'redis://cache:6379'
        WEBSOCKETS_ENABLED: true
        ADMIN_EMAIL: '${DIRECTUS_ADMIN}'
        ADMIN_PASSWORD: '${DIRECTUS_PASSWORD}'
        #EMAIL SETUP
        EMAIL_VERIFY_SETUP: '${EMAIL_VERIFY_SETUP}'
        EMAIL_FROM: '${EMAIL_FROM}'
        EMAIL_TRANSPORT: '${EMAIL_TRANSPORT}'
        EMAIL_SMTP_HOST: '${EMAIL_SMTP_HOST}'
        EMAIL_SMTP_PORT: '${EMAIL_SMTP_PORT}'
        EMAIL_SMTP_USER: '${EMAIL_SMTP_USER}'
        EMAIL_SMTP_PASSWORD: '${EMAIL_SMTP_PASSWORD}'
        EMAIL_SMTP_SECURE: '${EMAIL_SMTP_SECURE}'`

**Comment by hyn-lei** [comment]
1. run `npm i directus-extension-seo` at directus directory.
2. the result after restart directus. 
![image](https://github.com/codihaus/directus-extension-seo/assets/6426747/5931f72b-b2f5-4d04-86c7-2d4d0327e58a)

**Comment by bastianhilton** [comment]
> 1. npm i directus-extension-seo

why isn't this mentioned in the Readme.md file, if it wasn't for this issue then it would have been difficult to install this extension.

**Comment by BartTactick** [comment]
Incase someone is having this issue:
1. Go to your datamodel -> seo_setting -> enable the field "key" to show.
2. Go to the content -> seo setting -> create a new item with the key "setup"
And it should work

**Comment by Attacler** [comment]
Incase someone is having this issue:
1. Go to your datamodel -> seo_setting -> enable the field "key" to show.
2. Go to the content -> seo setting -> create a new item with the key "setup"
And it should work
