### ISSUE TITLE
TypeError: V.replace is not a function

### ISSUE THREAD

**Issue by prikr** [codihaus/directus-extension-seo#6]
Hi,

Once i installed this extension on a new instance, and created a Pages collection, added this extension, filled in the meta-title and description, i get the following error: 

```
TypeError: V.replace is not a function
    at Be (index.js:17427:42)
    at index.js:16944:144
    at At.fn (runtime-core.esm-bundler-zlSgKseS.js:9:9380)
    at At.run (runtime-core.esm-bundler-zlSgKseS.js:9:1517)
    at get value (runtime-core.esm-bundler-zlSgKseS.js:9:9624)
    at index.js:17520:29
    at s (runtime-core.esm-bundler-zlSgKseS.js:13:4787)
    at lc (runtime-core.esm-bundler-zlSgKseS.js:13:22035)
    at Proxy.<anonymous> (index.CqRcnUtk.entry.js:3475:128585)
    at en (runtime-core.esm-bundler-zlSgKseS.js:13:5097)
```

```
 at Be (index.js:17427:42):
 function Be(V = "") {
      var J;
      return (J = V == null ? void 0 : V.replace(/(<([^>]+)>)/gi, "").replaceAll(`
`, " ")) == null ? void 0 : J.substring(0, 255);
    }
```

**Comment by seadfeng** [comment]
Is Description output json?  I use `Flexible Editor` got the same issues, change to string output will be fix
